access_control: smartbugs/dataset/access_control
arithmetic: smartbugs/dataset/arithmetic
bad_randomness: smartbugs/dataset/bad_randomness
denial_of_service: smartbugs/dataset/denial_of_service
front_running: smartbugs/dataset/front_running
reentrancy: smartbugs/dataset/reentrancy
short_addresses: smartbugs/dataset/short_addresses
time_manipulation: smartbugs/dataset/time_manipulation
unchecked_ll_calls: smartbugs/dataset/unchecked_low_level_calls
other: smartbugs/dataset/other
